---
# Per environment values which override defaults in approved-premises-ui/values.yaml

generic-service:
  ingress:
    hosts:
      - short-term-accommodation-cas-2.hmpps.service.justice.gov.uk
    contextColour: green
    tlsSecretName: hmpps-community-accommodation-tier-2-prod-cert

  env:
    ENVIRONMENT: prod
    APPROVED_PREMISES_API_URL: 'https://approved-premises-api.hmpps.service.justice.gov.uk'
    INGRESS_URL: 'https://short-term-accommodation-cas-2.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api.prison.service.justice.gov.uk'
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_RESPONSE: 30000
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_DEADLINE: 30000
    IN_MAINTENANCE_MODE: false
    NOTES_DISABLED: 'true'

  namespace_secrets:
    hmpps-community-accommodation-tier-2-ui:
      TAG_MANAGER_ID: 'TAG_MANAGER_ID'
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'
      AUDIT_SQS_QUEUE_NAME: 'sqs_queue_name'

  allowlist: null
